version: "3"

services:
  airflow-web:
    image: ml-jku/airflow
    volumes:
      - ./dags:${AIRFLOW_HOME}/dags
    ports:
      - 8080:8080
    env_file:
      - airflow.env
    networks:
      - tpp
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    command: webserver

  flower-web:
    image: ml-jku/airflow
    restart: always
    ports:
      - 5555:5555
    env_file:
      - airflow.env
    networks:
      - tpp
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    command: flower

  airflow-scheduler:
    image: ml-jku/airflow
    restart: always
    depends_on:
      - airflow-web
    volumes:
      - ./dags:${AIRFLOW_HOME}/dags
    env_file:
      - airflow.env
    networks:
      - tpp
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    command: scheduler

  web:
    image: nginx:alpine
    volumes:
      - ./web/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - airflow-web
      - flower-web
    networks:
      - tpp

networks:
  tpp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
