version: "3"

services:
  airflow-web:
    build:
      context: .
      dockerfile: ./tools/docker/airflow.Dockerfile
    networks:
      - tpp
    environment:
      - AIRFLOW__WEBSERVER__BASE_URL=/airflow
    ports:
      - 8080:8080
    extra_hosts:
      - postgres:172.17.0.1
      - rabbitmq:172.17.0.1

  web:
    image: nginx:alpine
    volumes:
      - ./web/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - airflow-web
    networks:
      - tpp

networks:
  tpp:
    driver: bridge
