version: "3"

services:
  airflow-web:
    build:
      context: .
      dockerfile: ./tools/docker/airflow.Dockerfile
    restart: always
    volumes:
      - ./dags:${AIRFLOW_HOME}/dags
    networks:
      - tpp
    env_file:
      - airflow.env
    ports:
      - 8080:8080
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    command: webserver

  flower-web:
    build:
      context: .
      dockerfile: ./tools/docker/airflow.Dockerfile
    restart: always
    networks:
      - tpp
    env_file:
      - airflow.env
    ports:
      - 5555:5555
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    command: flower

  airflow-scheduler:
    build:
      context: .
      dockerfile: ./tools/docker/airflow.Dockerfile
    restart: always
    depends_on:
      - airflow-web
    volumes:
      - ./dags:${AIRFLOW_HOME}/dags
    networks:
      - tpp
    env_file:
      - airflow.env
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    command: flower

  web:
    image: nginx:alpine
    volumes:
      - ./web/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - airflow-web
      - flower-web
    networks:
      - tpp

networks:
  tpp:
    driver: bridge
