version: "3.7"

services:
  airflow-web:
    container_name: airflow-web
    image: ml-jku/airflow
    volumes:
      - ./dags:${AIRFLOW_HOME}/dags
    ports:
      - 8080:8080
    env_file:
      - .docker.env
    networks:
      - tpp
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    secrets:
      - ca-cert
      - postgres-client-key
      - postgres-client-cert
      - rabbitmq-client-key
      - rabbitmq-client-cert
    command: webserver

  flower-web:
    container_name: flower-web
    image: ml-jku/airflow
    restart: always
    ports:
      - 5555:5555
    env_file:
      - .docker.env
    networks:
      - tpp
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    secrets:
      - ca-cert
      - postgres-client-key
      - postgres-client-cert
      - rabbitmq-client-key
      - rabbitmq-client-cert
    command: flower

  airflow-scheduler:
    container_name: airflow-scheduler
    image: ml-jku/airflow
    restart: always
    depends_on:
      - airflow-web
    volumes:
      - ./dags:${AIRFLOW_HOME}/dags
    env_file:
      - .docker.env
    networks:
      - tpp
    extra_hosts:
      - ${DB_SERVER}:${DB_SERVER_DOCKER_IP}
    secrets:
      - ca-cert
      - postgres-client-key
      - postgres-client-cert
      - rabbitmq-client-key
      - rabbitmq-client-cert
    command: scheduler

  nginx-web:
    container_name: nginx-web
    image: nginx:alpine
    volumes:
      - ./deploy/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./deploy/html:/usr/share/nginx/html:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - airflow-web
      - flower-web
    networks:
      - tpp
    secrets:
      - ca-cert
      - nginx-key
      - nginx-cert
      - nginx-dhparam

networks:
  tpp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

secrets:
  ca-cert:
    file: ./secrets/ca-cert.pem
  nginx-dhparam:
    file: ./secrets/nginx/dhparam.pem
  nginx-key:
    file: ./secrets/nginx/server-key.pem
  nginx-cert:
    file: ./secrets/nginx/server-cert.pem
  postgres-client-key:
    file: ./secrets/client-key.pem
  postgres-client-cert:
    file: ./secrets/client-cert.pem
  rabbitmq-client-key:
    file: ./secrets/client-key.pem
  rabbitmq-client-cert:
    file: ./secrets/client-cert.pem
