name: tpp
channels:
  - rdkit
  - mordred-descriptor
  - defaults
dependencies:
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - backcall=0.1.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - decorator=4.4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jpeg=9b
  - libboost=1.67.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libtiff=4.0.10
  - libxml2=2.9.9
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - mordred=1.2.0
  - ncurses=6.1
  - networkx=2.3
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pandas=0.25.0
  - parso=0.5.0
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.1.0
  - pip=19.1.1
  - pixman=0.38.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py-boost=1.67.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pysocks=1.7.0
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.2
  - rdkit=2019.03.4.0
  - readline=7.0
  - requests=2.22.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - tqdm=4.32.1
  - traitlets=4.3.2
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
